tournament7h/tournament/urls.py
from django.conf.urls import url
from django.contrib import admin
from tournament.views import team as team_view
from tournament.views import player as player_view
from tournament.views import group as group_view
from tournament.views import game as game_view
from tournament.views import goal as top_scorers_view

admin.autodiscover()

urlpatterns = [
    url(r'^teams/$', view=team_view.TeamListView.as_view(), name="team_list"),
    url(r'^teams/(?P<pk>[0-9]+)/$', view=team_view.TeamDetailView.as_view(), name="team_detail"),

    url(r'^players/$',  'tournament.views.player.player_list_view', name="player_list"),
    url(r'^player/(?P<pk>[0-9]+)/$', view=player_view.PlayerDetailView.as_view(), name="player_detail"),

    url(r'^groups/$', view=group_view.GroupListView.as_view(), name="group_list"),
    url(r'^groups/(?P<pk>[0-9]+)/$', view=group_view.GroupDetailView.as_view(), name="group_detail"),

    url(r'^games/$', view=game_view.GameListView.as_view(), name="game_list"),
    url(r'^games/(?P<pk>[0-9]+)/$', view=game_view.GameDetailView.as_view(), name="game_detail"),

    url(r'^game_sheet/(?P<game_id>[0-9]+)/$', 'tournament.views.game.print_sheet', name="game_sheet"),

    url(r'^top_scorers/$', view=top_scorers_view.top_scorers_view, name="top_scorers_list"),
]

tournament7h/tournament7h/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import settings

admin.autodiscover()

urlpatterns = [
    url(r'^$', 'tournament.views.index.page', name="public_index"),
    url(r'^team-detail-(?P<pk>\d+)$', 'tournament.views.team_detail.page', name="team_detail"),
    url(r'^create-team$', 'tournament.views.create_team.page', name="create_team"),
    url(r'^connection/$', 'tournament.views.connections.page', name="public_connection"),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^tournament/', include('tournament.urls', namespace='tournament')),
    url(r'^img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    ]

tournament7h/tournament/models.py
from django.db import models
from operator import itemgetter


# Create your models here.
class Team(models.Model):
    name = models.CharField(max_length=30, verbose_name='Name')
    responsible = models.CharField(max_length=40, verbose_name='Team Responsible')
    image = models.ImageField(blank=True, upload_to='teams/')
    street = models.CharField(max_length=100, verbose_name='Street + Nr.')
    city = models.CharField(max_length=40, verbose_name='City')
    telephone = models.CharField(max_length=15, verbose_name='Telephone Nr.')

    def __str__(self):
        return self.name


class Player(models.Model):
    firstname = models.CharField(max_length=50, verbose_name='First Name')
    lastname = models.CharField(max_length=50, verbose_name='Last Name')
    number = models.IntegerField(verbose_name='Number')
    team = models.ForeignKey(Team, verbose_name="Team")

    class Meta:
        ordering = ['team', 'number']

    def __str__(self):
        return '%s %s' % (self.firstname, self.lastname)


class Location(models.Model):
    name = models.CharField(max_length=50, verbose_name='Location')

    def __str__(self):
        return self.name


class Group(models.Model):
    code = models.CharField(max_length=3, verbose_name='Group name')

    def get_standing(self):
        teams = []
        games = Game.objects.filter(group_id=self.id, finished=True)
        for game in games:
            if game.team_away not in teams:
                teams.append(game.team_away)
            if game.team_home not in teams:
                teams.append(game.team_home)

        standings = []
        for team in teams:
            team_values = {
                'team': team,
                'games_played': 0,
                'games_won': 0,
                'games_lost': 0,
                'games_draw': 0,
                'goals_made': 0,
                'goals_against': 0,
                'goals_ratio': 0,
                'total_points': 0,
            }
            for game in games:
                if game.team_away == team:
                    team_score = game.amount_away
                    opponent_score = game.amount_home
                elif game.team_home == team:
                    team_score = game.amount_home
                    opponent_score = game.amount_away
                else:
                    continue

                if team_score > opponent_score:
                    team_values.update({
                        'games_won': team_values['games_won'] + 1,
                        'total_points': team_values['total_points'] + 3
                    })
                elif team_score < opponent_score:
                    team_values.update({
                        'games_lost': team_values['games_lost'] + 1
                    })
                else:
                    team_values.update({
                        'games_draw': team_values['games_draw'] + 1,
                        'total_points': team_values['total_points'] + 1
                    })

                team_values.update({
                    'games_played': team_values['games_played'] + 1,
                    'goals_made': team_values['goals_made'] + team_score,
                    'goals_against': team_values['goals_against'] + opponent_score,
                    'goals_ratio': team_values['goals_ratio'] + team_score - opponent_score
                })

            standings.append(team_values)

        sorted_standings = sorted(standings, key=itemgetter('total_points', 'games_won', 'goals_ratio'), reverse=True)
        return sorted_standings

    def __str__(self):
        return '%s %s' % ('Group', self.code)


class Game(models.Model):
    team_home = models.ForeignKey(Team, related_name='team_home')
    team_away = models.ForeignKey(Team, related_name='team_away')
    amount_home = models.IntegerField(verbose_name='Score Home')
    amount_away = models.IntegerField(verbose_name='Score Away')
    group = models.ForeignKey(Group, verbose_name='Group')
    location = models.ForeignKey(Location, verbose_name='Location', blank=True, null=True)
    date = models.DateTimeField(verbose_name='Date', blank=True)
    finished = models.BooleanField(verbose_name='Finished')

    def __str__(self):
        return '%s, %s - %s' % (self.group, self.team_home, self.team_away)

    class Meta:
        ordering = ['date', 'group']


class Goal(models.Model):
    player = models.ForeignKey(Player, verbose_name='Player')
    game = models.ForeignKey(Game, verbose_name='Game')
    amount = models.IntegerField()

    def __str__(self):
        return '%s, %d goals' % (self.player, self.amount)


class FairPlay(models.Model):
    team = models.ForeignKey(Team, verbose_name='Team')
    game = models.ForeignKey(Game, verbose_name='Game')
    amount = models.IntegerField()

    def __str__(self):
        return '%s, %d/10' % (self.team, self.amount)

tournament7h/tournament/views.py
from django.shortcuts import render

# Create your views here.

tournament7h/tournament/views/connections.py
from django.shortcuts import render
# View for connection page.

def page(request):
    return render(request, 'public/connection.html')

tournament7h/tournament/views/create_team.py
from django.shortcuts import render
from tournament.models import Team
from django import forms
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

def page(request):
    if len(request.POST) > 0:
        form = FormSupervisor(request.POST)

        if form.is_valid():
            form.save(commit=True)
            # If the form is valid, we store the data in a model record in
            # the form.
            return HttpResponseRedirect(reverse('public_index'))
            # This line is used to redirect to the specified URL. We use the
            # reverse() function to get the URL from its name defines urls.py.
        else:
            return render(request, 'public/create_team.html', {'form': form})
    else:
        form = FormSupervisor()
        return render(request, 'public/create_team.html', {'form': form})

class FormSupervisor(forms.ModelForm):
    # Here we create a class that inherits from ModelForm.

    class Meta:
        # We extend the Meta class of the ModelForm. It is this class that
        # will allow us to define the properties of ModelForm.

        model = Team
        # We define the model that should be based on the form.

        exclude = ('date_created', 'last_connexion', )
        # We exclude certain fields of this form. It would also have been
        # possible to do the opposite. That is to say with the fields property,
        # we have defined the desired fields in the form.

tournament7h/tournament/views/game.py
from django.views.generic import ListView, DetailView
from tournament.models import Game
import cStringIO as StringIO
import ho.pisa as pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from cgi import escape
from django.shortcuts import get_object_or_404


class GameListView(ListView):
    model = Game
    template_name = 'public/game_list.html'


class GameDetailView(DetailView):
    model = Game
    template_name = 'public/game_detail.html'


def print_sheet(request, game_id):
    game = get_object_or_404(Game, pk=game_id)

    return render_to_pdf(
        'game_sheet.html',
        {
            'pagesize': 'A4',
            'game': game
        }
    )

def render_to_pdf(template_src, context_dict):
    template = get_template(template_src)
    context = Context(context_dict)
    html  = template.render(context)
    result = StringIO.StringIO()

    pdf = pisa.pisaDocument(StringIO.StringIO(html.encode("ISO-8859-1")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))

tournament7h/tournament/views/goal.py
from django.shortcuts import render
from django.db.models import Sum

from tournament.models import Goal, Player


def top_scorers_view(request):
    scorers = Goal.objects.values('player_id').annotate(sum_goals=Sum('amount')).order_by('-sum_goals')

    for scorer in scorers:
        scorer.update({
            'player': Player.objects.get(pk=scorer['player_id'])
        })

    values = {
        'top_scorers': scorers
    }
    return render(request, 'public/top_scorers_list.html', values)

tournament7h/tournament/views/group.py
from django.views.generic import ListView, DetailView
from tournament.models import Group


class GroupListView(ListView):
    model = Group
    template_name = 'public/group_list.html'


class GroupDetailView(DetailView):
    model = Group
    template_name = 'public/group_detail.html'

tournament7h/tournament/views/index.py
from django.shortcuts import render
from tournament.models import Team


def page(request):
    all_teams = Team.objects.all()
    return render(request, 'public/index.html',
                  {
                      'teams': all_teams}
                  )

tournament7h/tournament/views/player.py
from django.views.generic import DetailView
from tournament.models import Player, Team
from django.shortcuts import render


def player_list_view(request):
    players = {}
    alphabet = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
                'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

    for letter in alphabet:
        players.update({
            letter: Player.objects.filter(lastname__startswith=letter).order_by('lastname')
        })

    return render(request, 'public/player_list.html',
                  {
                      'players': players
                  }
                  )


class PlayerDetailView(DetailView):
    model = Player
    template_name = 'public/player_detail.html'

tournament7h/tournament/views/team.py
from django.views.generic import ListView, DetailView
from tournament.models import Team


class TeamListView(ListView):
    model = Team
    template_name = 'public/team_list.html'


class TeamDetailView(DetailView):
    model = Team
    template_name = 'public/team_detail.html'

tournament7h/tournament/views/team_detail.py
from django.shortcuts import render
from tournament.models import Team


def page(request, pk):
    team = Team.objects.get(id=pk)
    return render(request, 'public/team_detail.html', {'team': team})

tournament7h/tournament/templates/base.html
{% load staticfiles %}

<html>
<head>
    <title>
        {% block title_html %}{% endblock %}
    </title>

    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "bootstrap3/dist/css/bootstrap.css" %}" rel="stylesheet" type="text/css"/>

    <script src="{% static "jquery/jquery-1.11.3.js" %}"></script>
    <script src="{% static "bootstrap3/dist/js/bootstrap.min.js" %}"></script>

</head>

<body>

<div class="container">



    <!-- Static navbar -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Tournament 7H</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'tournament:game_list' %}">Games</a></li>
                    <li><a href="{% url 'tournament:group_list' %}">Standings</a></li>
                    <li><a href="{% url 'tournament:top_scorers_list' %}">Top Scorers</a></li>
                    <li><a href="{% url 'tournament:team_list' %}">Teams</a></li>
                    <li><a href="{% url 'tournament:player_list' %}">Players</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
    </nav>
    <article>
        {% block article_content %}{% endblock %}
    </article>

</div>
</body>
</html>

tournament7h/tournament/templates/game_sheet.html
{% load staticfiles %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>My Title</title>

    <link href="../static/bootstrap3/dist/css/bootstrap.css" rel="stylesheet" type="text/css"/>


    <style type="text/css">
        @page {
            size: {{ pagesize }};
            margin: 2cm;
        }
        .player-table{
            border: 1px solid black;
        }
        .content-column{
            padding: 5px;
        }
        .player-table {
            width: 375px;
            vertical-align: text-top;
        }
        .team-header{
            font-size: xx-large;
            text-align: center;
        }
        #headerContent{
            text-align: center;
        }
        #otherContent{
            margin-top: 100px;
        }
        #remarks{
            text-align: center;
        }

    </style>
</head>
<body>
<div id="headerContent">
    <h1>Toernooi Zevenhuizen 2015</h1>
    <h2>{{ game.date|date:'d/m H:i' }}</h2>
    <h2>{{ game.location.name }}</h2>
</div>

<div id="teamContent">
    <table>
        <tr>
            <td class="content-column" valign="top">
                <h1 class="team-header">{{ game.team_home }}</h1>
                <table class="player-table">
                    <tr>
                        <th width="50px">Nr.</th>
                        <th width="250px">Naam</th>
                        <th width="75px">Goals</th>
                    </tr>
                    {% for player in game.team_home.player_set.all %}
                        <tr>
                            <td width="50px">{{ player.number }}</td>
                            <th width="250px">{{ player.firstname }} {{ player.lastname }}</th>
                            <td width="75px"></td>
                        </tr>
                    {% endfor %}
                </table>
            </td>
            <td class="content-column" valign="top">
                <h1 class="team-header">{{ game.team_away }}</h1>
                <table class="player-table">
                    <tr>
                        <th width="50px">Nr.</th>
                        <th width="250px">Naam</th>
                        <th width="75px">Goals</th>
                    </tr>
                    {% for player in game.team_away.player_set.all %}
                        <tr>
                            <td width="50px">{{ player.number }}</td>
                            <th width="250px">{{ player.firstname }} {{ player.lastname }}</th>
                            <td width="75px"></td>
                        </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
    </table>
</div>

<div id="otherContent">
    <table>
        <tr>
            <td valign="top" class="team-header">
                Handtekening thuisploeg
                <p>........................................</p>
            </td>
            <td valign="top" class="team-header">
                Handtekening uitploeg
                <p>........................................</p>
            </td>
        </tr>
    </table>
    <br />
    <br />
</div>

<div id="remarks">
    <h1>Opmerkingen scheidsrechter: </h1>
</div>
</body>
</html>